### ISSUE TITLE
System Todo

### ISSUE THREAD

**Issue by Jasdoge** [Shadowplayers-spf/ShadowServ#1]
- [x] Fix port forwarding from home

REGISTRATIONS:
- [x] Log in auto after registering
- [x] Add back button

LOGIN
- [x] Validate login
- [x] Go to main page

STUFF
- [ ] Logged out response to go back to login page if session expired
